### ISSUE TITLE
When i submit form showing "Sorry but your message could not be sent, try again later"

### ISSUE THREAD

**Issue by Bablubaghel** [philipbeel/contactable#19]
I Think i have done all the thing to my best  to integrate this plugin correctly but after submit my form showing "Sorry but your message could not be sent, try again later".
(someone please help me what is going wrong with me.)

Thanks & Regard
Bablu Baghel

**Comment by philipbeel** [comment]
The plugin needs to be run on a LAMP stack running PHP in order to submit the form. 

This error is often caused when the php mail file is not being located correctly. In chrome open the developer tools and what the network tab when you submit the form. You will see a 404 is the file cannot be located. 

To resolve this, move the form into the correct location on the server.
